---
title: "Variation in use of East Asian Late Paleolithic weapons: A study of tip cross-sectional area of stemmed points from Korea"
author:
  - Gayoung Park:
      institute: uw
      correspondence: "yes"
      email: gayoungp@uw.edu
  - Marlize Lombard:
      institute: uj
  - Ben Marwick:
      institute: uw
  - Donghee Chong:
      institute: uk
  
institute:
  - uw:
    name: Department of Anthropology, University of Washington
    address: Seattle, WA, USA
  - uj:
    name: Palaeo-Research Institute, University of Johannesburg
    address: Johannesburg, South Africa
  - uk:
    name: Department of History, Kyung Hee University
    address: Seoul, South Korea

format: 
  docx:
    reference-doc: "../templates/template.docx" # Insert path for the DOCX file
execute:
  echo: false
  warning: false
  message: false
  comment: "#>"
  fig-path: "../figures/"
  fig-dpi: 600
editor: visual
date: now
date-format: long
title-block-published: "Last updated" 

bibliography: references.bib
csl: "../templates/journal-of-archaeological-science.csl" # Insert path for the bib-style

abstract: |
 The introduction of blade technology, stemmed points, end scrapers, burins, denticulates, and finer grained materials led to the transition from the Early to Late Paleolithic in Korea. Stemmed points have been considered a representative tool that led this whole set of changes. In this research, we examine the function of stemmed points to understand the role that they played during the technological transition as well as throughout the Late Paleolithic. Our main questions are: What were stemmed points used for? How diverse were their functions? What are the temporal patterns in stemmed point functions? We measured tip cross-sectional areas (TCSA) to discriminate different functional classes of projectile points, for example, poisoned arrowheads or thrusting spear. We analyze TCSA with other variables including raw materials, weight, site and radiocarbon dates. Our results show that the stemmed points mostly functioned as javelins and thrusting spear tips, with smaller numbers as dart tips and arrowheads. TCSA values are depending on size and raw material types. We found different usage of stemmed points in different sites, which could indicate people used stemmed points in different ways depending on the environment. However, some sites show a wide range of TCSA values that represent multi-purpose usage of stemmed points. The temporal pattern of TCSA values is one of little change throughout the Late Paleolithic period. We conclude that stemmed points were mainly used as Javelin but they were multi-functional tools.
keywords: |
  Stemmed points; Korean Paleolithic; Tip Cross-Sectional Area
---

# Introduction {.unnumbered}

With the introduction of new technologies, the Korean Paleolithic transitioned from the Early to the Late Paleolithic periods. The transition includes blade technology, stemmed points, end scrapers, burins, denticulates, etc [@bae2017origin; @nakazawa2018quaternary; @bae2017late; @lee2017korean; @seong2016eastern]. Another notable change is the selective use of raw materials along with the emergence of new tools. Previously quartzite and vein quartz were the most commonly used for core and flake tools but finer grained materials such as silicified tuff (shale), chert, hornfels, and obsidian became more important to the lithic technology during the Late Paleolithic. While people still used coarse materials with existing tools, they selectively chose finer materials for newly introduced tools. [@Seong_2003; @seong2004quartzite]. Stemmed points are considered the first evidence of the new technology, as well as the Late Paleolithic, since they led to the whole set of changes [@seong2016eastern; @seong2008tanged]. This is related to the fact that stemmed points originate from Korea in Northeast Asia and have a close association with mobility, site formation, and occupation diversity [@o2018origins; @Chong_2021; @park2022did]. Despite the importance of stemmed points, only a few studies have examined their use, whereas researchers often discuss stemmed points relating to their origin and chronology of the Korean Late Paleolithic and their relationship with Japan [@chang2013human; @Park_2013; @lee2019were; @Chong_2021].[@chang2013human; @Park_2013; @lee2019were; @Chong_2021]. 

To understand the role stemmed points played in the technological transition, this study examines the functions of stemmed points. We use the tip cross-sectional area (TCSA) metric to calculate artifact function and compare the results to other archaeological and ethnographic assemblages based on the idea that different shapes correspond to different functions [@lombard2021variation]. We then explore the relationship between and function raw materials, artifact size and discard location, and how these change over time. Our main questions are: What were stemmed points used for? How diverse were their functions? What are the temporal patterns in stemmed point functions? As part of our discussion, we examine possible connections between the roles of stemmed points and population dynamics or environmental change during the Late Paleolithic period. In order to understand how a certain weapon-tip type was chosen, we premise that human groups had the cognitive capacity to choose proper weapons depending on their hunting strategies and socio-environmental circumstances.

